//
// RhymeAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



open class RhymeAPI: APIBase {
    /**
     インを取得
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getRhyme(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
        getRhymeWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     インを取得
     - GET /
     - インを取得
     - examples: [{contentType=application/json, example="aeiou"}]

     - returns: RequestBuilder<String> 
     */
    open class func getRhymeWithRequestBuilder() -> RequestBuilder<String> {
        let path = "/"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<String>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
